// SPDX-License-Identifier: Apache-2.0

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	ErrorCodeFACTTABLENOTFOUND    ErrorCode = "FACT_TABLE_NOT_FOUND"
	ErrorCodeFACTTABLEUNAVAILABLE ErrorCode = "FACT_TABLE_UNAVAILABLE"
	ErrorCodeINDEXUNAVAILABLE     ErrorCode = "INDEX_UNAVAILABLE"
	ErrorCodeINTERNAL             ErrorCode = "INTERNAL"
	ErrorCodeMETHODNOTALLOWED     ErrorCode = "METHOD_NOT_ALLOWED"
	ErrorCodeNOTFOUND             ErrorCode = "NOT_FOUND"
	ErrorCodeSTORAGEDOWN          ErrorCode = "STORAGE_DOWN"
	ErrorCodeUNAUTHORIZED         ErrorCode = "UNAUTHORIZED"
	ErrorCodeUNKNOWNSCOPEKEY      ErrorCode = "UNKNOWN_SCOPE_KEY"
	ErrorCodeUPSTREAMTIMEOUT      ErrorCode = "UPSTREAM_TIMEOUT"
	ErrorCodeUPSTREAMUNAVAILABLE  ErrorCode = "UPSTREAM_UNAVAILABLE"
	ErrorCodeVALIDATIONFAILED     ErrorCode = "VALIDATION_FAILED"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeFACTTABLENOTFOUND:
		return true
	case ErrorCodeFACTTABLEUNAVAILABLE:
		return true
	case ErrorCodeINDEXUNAVAILABLE:
		return true
	case ErrorCodeINTERNAL:
		return true
	case ErrorCodeMETHODNOTALLOWED:
		return true
	case ErrorCodeNOTFOUND:
		return true
	case ErrorCodeSTORAGEDOWN:
		return true
	case ErrorCodeUNAUTHORIZED:
		return true
	case ErrorCodeUNKNOWNSCOPEKEY:
		return true
	case ErrorCodeUPSTREAMTIMEOUT:
		return true
	case ErrorCodeUPSTREAMUNAVAILABLE:
		return true
	case ErrorCodeVALIDATIONFAILED:
		return true
	default:
		return false
	}
}

// Defines values for FactsLookupStatus.
const (
	FactsLookupStatusFOUND    FactsLookupStatus = "FOUND"
	FactsLookupStatusNOTFOUND FactsLookupStatus = "NOT_FOUND"
)

// Valid indicates whether the value is a known member of the FactsLookupStatus enum.
func (e FactsLookupStatus) Valid() bool {
	switch e {
	case FactsLookupStatusFOUND:
		return true
	case FactsLookupStatusNOTFOUND:
		return true
	default:
		return false
	}
}

// Defines values for Language.
const (
	LanguageEN Language = "EN"
	LanguageZH Language = "ZH"
)

// Valid indicates whether the value is a known member of the Language enum.
func (e Language) Valid() bool {
	switch e {
	case LanguageEN:
		return true
	case LanguageZH:
		return true
	default:
		return false
	}
}

// Defines values for SearchStatus.
const (
	SearchStatusHIT     SearchStatus = "HIT"
	SearchStatusNOMATCH SearchStatus = "NO_MATCH"
)

// Valid indicates whether the value is a known member of the SearchStatus enum.
func (e SearchStatus) Valid() bool {
	switch e {
	case SearchStatusHIT:
		return true
	case SearchStatusNOMATCH:
		return true
	default:
		return false
	}
}

// Error The single error envelope body: an error code plus interpolation params. Message is diagnostic English and is never shown to end users.
type Error struct {
	// Code Machine-readable failure identifier. The service never localizes.
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`

	// Params Machine-readable details, for example {"field": "topK"}.
	Params *map[string]interface{} `json:"params,omitempty"`
}

// ErrorCode Machine-readable failure identifier. The service never localizes.
type ErrorCode string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error The single error envelope body: an error code plus interpolation params. Message is diagnostic English and is never shown to end users.
	Error Error `json:"error"`
}

// FactsLookupRequest defines model for FactsLookupRequest.
type FactsLookupRequest struct {
	// At Date at which the row must be valid. Omit for the current date in the service time zone (KB_TIMEZONE, default UTC).
	At *openapi_types.Date `json:"at,omitempty"`

	// Key Key column values. Must cover exactly the key columns of the table mapping.
	Key map[string]interface{} `json:"key"`
}

// FactsLookupResponse defines model for FactsLookupResponse.
type FactsLookupResponse struct {
	// Row Typed row values keyed by column name. Null when status is NOT_FOUND.
	Row       *map[string]interface{} `json:"row,omitempty"`
	SourceRef *string                 `json:"sourceRef,omitempty"`
	Status    FactsLookupStatus       `json:"status"`
	ValidFrom *openapi_types.Date     `json:"validFrom,omitempty"`
	ValidTo   *openapi_types.Date     `json:"validTo,omitempty"`
}

// FactsLookupStatus defines model for FactsLookupStatus.
type FactsLookupStatus string

// Language Content language. EN maps to the index faq_en, ZH to faq_zh.
type Language string

// SearchItem defines model for SearchItem.
type SearchItem struct {
	// Answer Short, speakable answer text.
	Answer string `json:"answer"`

	// ID Stable identifier of the published Q&A.
	ID       string `json:"id"`
	Question string `json:"question"`

	// Score Meilisearch ranking score for a pure-vector search, (1 + cosine) / 2, so it ranges roughly 0.5 to 1 and an unrelated document still scores about 0.5. Callers must decide on `status` (HIT or NO_MATCH, gated by the service's per-index threshold) and must not apply their own threshold to `score`.
	Score float32 `json:"score"`

	// SourceRef Where the answer came from, for example a file name and heading path.
	SourceRef string `json:"sourceRef"`
}

// SearchLatencyMs Per-stage latency of this request in milliseconds.
type SearchLatencyMs struct {
	Embedding float32 `json:"embedding"`
	Search    float32 `json:"search"`
	Total     float32 `json:"total"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	// Language Content language. EN maps to the index faq_en, ZH to faq_zh.
	Language Language `json:"language"`

	// Query The caller's question.
	Query string `json:"query"`

	// Scope Exact-match filter. Every key must be one of the configured scope keys, otherwise the request fails with UNKNOWN_SCOPE_KEY. A published item that carries no value for a key (its source file path does not name one) is global for that key and matches any value of it.
	Scope *map[string]string `json:"scope,omitempty"`

	// TimeoutMs Request budget in milliseconds. Defaults to and is capped by the service configuration.
	TimeoutMs *int `json:"timeoutMs,omitempty"`

	// TopK Maximum number of items returned.
	TopK *int `json:"topK,omitempty"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	// Items Empty when status is NO_MATCH.
	Items []SearchItem `json:"items"`

	// LatencyMs Per-stage latency of this request in milliseconds.
	LatencyMs SearchLatencyMs `json:"latencyMs"`

	// Status HIT or NO_MATCH. NO_MATCH is decided server-side by a per-index threshold on the ranking score.
	Status SearchStatus `json:"status"`
}

// SearchStatus defines model for SearchStatus.
type SearchStatus string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// GatewayTimeout defines model for GatewayTimeout.
type GatewayTimeout = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// LookupFactJSONRequestBody defines body for LookupFact for application/json ContentType.
type LookupFactJSONRequestBody = FactsLookupRequest

// SearchFaqJSONRequestBody defines body for SearchFaq for application/json ContentType.
type SearchFaqJSONRequestBody = SearchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// LookupFact Look up one row of a fact table by its key
	// (POST /v1/facts/{table}/lookup)
	LookupFact(w http.ResponseWriter, r *http.Request, table string)
	// SearchFaq Search the live FAQ index of one language
	// (POST /v1/search)
	SearchFaq(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// LookupFact Look up one row of a fact table by its key
// (POST /v1/facts/{table}/lookup)
func (_ Unimplemented) LookupFact(w http.ResponseWriter, r *http.Request, table string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SearchFaq Search the live FAQ index of one language
// (POST /v1/search)
func (_ Unimplemented) SearchFaq(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LookupFact operation middleware
func (siw *ServerInterfaceWrapper) LookupFact(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "table" -------------
	var table string

	err = runtime.BindStyledParameterWithOptions("simple", "table", chi.URLParam(r, "table"), &table, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "table", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LookupFact(w, r, table)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchFaq operation middleware
func (siw *ServerInterfaceWrapper) SearchFaq(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchFaq(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/facts/{table}/lookup", wrapper.LookupFact)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/search", wrapper.SearchFaq)
	})

	return r
}
