// SPDX-License-Identifier: Apache-2.0

// Package store owns the PostgreSQL connection pool, the embedded goose
// migrations and the typed queries (generated by sqlc into ./queries).
package store

import (
	"context"
	"database/sql"
	"embed"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jackc/pgx/v5/stdlib"
	"github.com/pressly/goose/v3"

	"github.com/rasonyang/aicc-knowledge/internal/store/queries"
)

//go:embed migrations/*.sql
var migrationFS embed.FS

// migrationLockKey is the advisory lock that serializes migrators: two
// processes starting together must not run goose concurrently.
const migrationLockKey int64 = 0x4b4e4f57 // "KNOW"

// Store bundles the pool and the generated queries.
type Store struct {
	Pool    *pgxpool.Pool
	Queries *queries.Queries
}

// Open connects to PostgreSQL and verifies the connection.
func Open(ctx context.Context, dsn string, maxConns int) (*Store, error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("parse database url: %w", err)
	}
	if maxConns > 0 {
		cfg.MaxConns = int32(maxConns)
	}
	cfg.MaxConnLifetime = time.Hour
	cfg.HealthCheckPeriod = 30 * time.Second
	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("open pool: %w", err)
	}
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping database: %w", err)
	}
	return &Store{Pool: pool, Queries: queries.New(pool)}, nil
}

// Close releases the pool.
func (s *Store) Close() { s.Pool.Close() }

// Ping checks the database for /readyz.
func (s *Store) Ping(ctx context.Context) error { return s.Pool.Ping(ctx) }

// Migrate applies every pending migration under an advisory lock. It is
// called at startup by serve and by every CLI subcommand that touches the
// database.
func (s *Store) Migrate(ctx context.Context) error {
	if s.Pool.Config().MaxConns < 2 {
		return errors.New("migrate needs a pool of at least 2 connections")
	}
	lockConn, err := s.Pool.Acquire(ctx)
	if err != nil {
		return fmt.Errorf("acquire migration lock connection: %w", err)
	}
	defer lockConn.Release()
	if _, err := lockConn.Exec(ctx, "SELECT pg_advisory_lock($1)", migrationLockKey); err != nil {
		return fmt.Errorf("take migration lock: %w", err)
	}
	defer func() {
		// Unlock on a fresh context: ctx may be the reason we are leaving.
		uctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_, _ = lockConn.Exec(uctx, "SELECT pg_advisory_unlock($1)", migrationLockKey)
	}()

	db := stdlib.OpenDBFromPool(s.Pool)
	defer db.Close()
	p, err := newProvider(db)
	if err != nil {
		return err
	}
	if _, err := p.Up(ctx); err != nil {
		return fmt.Errorf("apply migrations: %w", err)
	}
	return nil
}

// MigrateDown rolls every migration back. Tests use it; no command does.
func (s *Store) MigrateDown(ctx context.Context) error {
	db := stdlib.OpenDBFromPool(s.Pool)
	defer db.Close()
	p, err := newProvider(db)
	if err != nil {
		return err
	}
	if _, err := p.DownTo(ctx, 0); err != nil {
		return fmt.Errorf("roll back migrations: %w", err)
	}
	return nil
}

// MigrationVersions returns the applied and the latest embedded version.
func (s *Store) MigrationVersions(ctx context.Context) (applied, latest int64, err error) {
	db := stdlib.OpenDBFromPool(s.Pool)
	defer db.Close()
	p, err := newProvider(db)
	if err != nil {
		return 0, 0, err
	}
	applied, err = p.GetDBVersion(ctx)
	if err != nil {
		return 0, 0, err
	}
	for _, m := range p.ListSources() {
		latest = max(latest, m.Version)
	}
	return applied, latest, nil
}

func newProvider(db *sql.DB) (*goose.Provider, error) {
	fsys, err := fsSub()
	if err != nil {
		return nil, err
	}
	p, err := goose.NewProvider(goose.DialectPostgres, db, fsys, goose.WithDisableGlobalRegistry(true))
	if err != nil {
		return nil, fmt.Errorf("create migration provider: %w", err)
	}
	return p, nil
}
