// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidates.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCandidatesOfVersion = `-- name: CountCandidatesOfVersion :one

SELECT count(*) FROM candidates WHERE file_version_id = $1
`

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) CountCandidatesOfVersion(ctx context.Context, fileVersionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCandidatesOfVersion, fileVersionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertCandidate = `-- name: InsertCandidate :execrows
INSERT INTO candidates (file_version_id, section_ordinal, language, question, alternate_questions, answer,
                        source_ref, flags, content_hash, prompt_version, model, generated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (file_version_id, content_hash) DO NOTHING
`

type InsertCandidateParams struct {
	FileVersionID      uuid.UUID          `json:"fileVersionId"`
	SectionOrdinal     *int32             `json:"sectionOrdinal"`
	Language           string             `json:"language"`
	Question           string             `json:"question"`
	AlternateQuestions []string           `json:"alternateQuestions"`
	Answer             string             `json:"answer"`
	SourceRef          string             `json:"sourceRef"`
	Flags              []string           `json:"flags"`
	ContentHash        []byte             `json:"contentHash"`
	PromptVersion      string             `json:"promptVersion"`
	Model              string             `json:"model"`
	GeneratedAt        pgtype.Timestamptz `json:"generatedAt"`
}

// Idempotent per (file_version_id, content_hash): a repeat inserts nothing.
func (q *Queries) InsertCandidate(ctx context.Context, arg InsertCandidateParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertCandidate,
		arg.FileVersionID,
		arg.SectionOrdinal,
		arg.Language,
		arg.Question,
		arg.AlternateQuestions,
		arg.Answer,
		arg.SourceRef,
		arg.Flags,
		arg.ContentHash,
		arg.PromptVersion,
		arg.Model,
		arg.GeneratedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCandidateReview = `-- name: InsertCandidateReview :exec
INSERT INTO candidate_reviews (candidate_id, action, reviewer, before, after, source_file_name)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCandidateReviewParams struct {
	CandidateID    uuid.UUID `json:"candidateId"`
	Action         string    `json:"action"`
	Reviewer       string    `json:"reviewer"`
	Before         []byte    `json:"before"`
	After          []byte    `json:"after"`
	SourceFileName string    `json:"sourceFileName"`
}

func (q *Queries) InsertCandidateReview(ctx context.Context, arg InsertCandidateReviewParams) error {
	_, err := q.db.Exec(ctx, insertCandidateReview,
		arg.CandidateID,
		arg.Action,
		arg.Reviewer,
		arg.Before,
		arg.After,
		arg.SourceFileName,
	)
	return err
}

const listCandidatesForExport = `-- name: ListCandidatesForExport :many
SELECT c.id, c.language, c.question, c.alternate_questions, c.answer, c.flags, c.source_ref, c.content_hash,
       c.state, COALESCE(c.review_note, '')::text AS review_note, COALESCE(s.body, '')::text AS section_body
FROM candidates c
JOIN file_versions v ON v.id = c.file_version_id
JOIN source_files sf ON sf.id = v.source_file_id
LEFT JOIN parsed_sections s ON s.file_version_id = c.file_version_id AND s.ordinal = c.section_ordinal AND s.source_ref = c.source_ref
WHERE c.state = ANY($1::text[])
  AND ($2::text = '' OR c.language = $2::text)
ORDER BY sf.object_key, v.version_no, c.section_ordinal NULLS FIRST, c.created_at, c.id
`

type ListCandidatesForExportParams struct {
	States   []string `json:"states"`
	Language string   `json:"language"`
}

type ListCandidatesForExportRow struct {
	ID                 uuid.UUID `json:"id"`
	Language           string    `json:"language"`
	Question           string    `json:"question"`
	AlternateQuestions []string  `json:"alternateQuestions"`
	Answer             string    `json:"answer"`
	Flags              []string  `json:"flags"`
	SourceRef          string    `json:"sourceRef"`
	ContentHash        []byte    `json:"contentHash"`
	State              string    `json:"state"`
	ReviewNote         string    `json:"reviewNote"`
	SectionBody        string    `json:"sectionBody"`
}

// Candidates in deterministic order for the review workbook, with the text of
// the section they came from (empty when the section is gone).
func (q *Queries) ListCandidatesForExport(ctx context.Context, arg ListCandidatesForExportParams) ([]ListCandidatesForExportRow, error) {
	rows, err := q.db.Query(ctx, listCandidatesForExport, arg.States, arg.Language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCandidatesForExportRow{}
	for rows.Next() {
		var i ListCandidatesForExportRow
		if err := rows.Scan(
			&i.ID,
			&i.Language,
			&i.Question,
			&i.AlternateQuestions,
			&i.Answer,
			&i.Flags,
			&i.SourceRef,
			&i.ContentHash,
			&i.State,
			&i.ReviewNote,
			&i.SectionBody,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveCandidateSections = `-- name: ListLiveCandidateSections :many
SELECT DISTINCT section_ordinal, source_ref FROM candidates
WHERE file_version_id = $1 AND state <> 'STALE' AND section_ordinal IS NOT NULL
`

type ListLiveCandidateSectionsRow struct {
	SectionOrdinal *int32 `json:"sectionOrdinal"`
	SourceRef      string `json:"sourceRef"`
}

// The (ordinal, source_ref) of every section of a version that has a
// candidate in any state but STALE. Generation uses it to find Q&A rows that
// still need one.
func (q *Queries) ListLiveCandidateSections(ctx context.Context, fileVersionID uuid.UUID) ([]ListLiveCandidateSectionsRow, error) {
	rows, err := q.db.Query(ctx, listLiveCandidateSections, fileVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLiveCandidateSectionsRow{}
	for rows.Next() {
		var i ListLiveCandidateSectionsRow
		if err := rows.Scan(&i.SectionOrdinal, &i.SourceRef); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCandidateForReview = `-- name: LockCandidateForReview :one
SELECT c.id, c.file_version_id, c.language, c.question, c.alternate_questions, c.answer, c.source_ref, c.flags,
       c.state, c.content_hash, c.review_note,
       (v.superseded_at IS NULL AND v.state = 'PARSED')::bool AS version_is_current
FROM candidates c
JOIN file_versions v ON v.id = c.file_version_id
WHERE c.id = $1
FOR UPDATE OF c
`

type LockCandidateForReviewRow struct {
	ID                 uuid.UUID `json:"id"`
	FileVersionID      uuid.UUID `json:"fileVersionId"`
	Language           string    `json:"language"`
	Question           string    `json:"question"`
	AlternateQuestions []string  `json:"alternateQuestions"`
	Answer             string    `json:"answer"`
	SourceRef          string    `json:"sourceRef"`
	Flags              []string  `json:"flags"`
	State              string    `json:"state"`
	ContentHash        []byte    `json:"contentHash"`
	ReviewNote         *string   `json:"reviewNote"`
	VersionIsCurrent   bool      `json:"versionIsCurrent"`
}

// The candidate the review import needs, locked for the rest of the
// transaction. current_ok says whether its file version is still the current,
// PARSED one.
func (q *Queries) LockCandidateForReview(ctx context.Context, id uuid.UUID) (LockCandidateForReviewRow, error) {
	row := q.db.QueryRow(ctx, lockCandidateForReview, id)
	var i LockCandidateForReviewRow
	err := row.Scan(
		&i.ID,
		&i.FileVersionID,
		&i.Language,
		&i.Question,
		&i.AlternateQuestions,
		&i.Answer,
		&i.SourceRef,
		&i.Flags,
		&i.State,
		&i.ContentHash,
		&i.ReviewNote,
		&i.VersionIsCurrent,
	)
	return i, err
}

const markCandidatesOfWithdrawnSectionsStale = `-- name: MarkCandidatesOfWithdrawnSectionsStale :execrows
UPDATE candidates c
SET state = 'STALE',
    review_note = COALESCE(NULLIF(c.review_note, '') || E'\n', '') || 'SECTION_WITHDRAWN'
WHERE c.file_version_id = $1
  AND c.state <> 'STALE'
  AND c.section_ordinal IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM parsed_sections s
      WHERE s.file_version_id = c.file_version_id AND s.ordinal = c.section_ordinal AND s.source_ref = c.source_ref)
`

// Called where a version's sections are rewritten. A candidate is tied to its
// section by (ordinal, source_ref); one whose section no longer exists can no
// longer be checked against its source. The reason is appended to any note.
func (q *Queries) MarkCandidatesOfWithdrawnSectionsStale(ctx context.Context, fileVersionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markCandidatesOfWithdrawnSectionsStale, fileVersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markQACandidatesOfRowStale = `-- name: MarkQACandidatesOfRowStale :execrows
UPDATE candidates
SET state = 'STALE',
    review_note = COALESCE(NULLIF(review_note, '') || E'\n', '') || 'QA_ROW_CHANGED'
WHERE file_version_id = $1 AND section_ordinal = $2 AND source_ref = $3
  AND state <> 'STALE' AND prompt_version LIKE 'qa-%'
`

type MarkQACandidatesOfRowStaleParams struct {
	FileVersionID  uuid.UUID `json:"fileVersionId"`
	SectionOrdinal *int32    `json:"sectionOrdinal"`
	SourceRef      string    `json:"sourceRef"`
}

// A Q&A row changed under the same (ordinal, source_ref): the candidates
// imported from it (prompt_version qa-*) no longer match their source.
func (q *Queries) MarkQACandidatesOfRowStale(ctx context.Context, arg MarkQACandidatesOfRowStaleParams) (int64, error) {
	result, err := q.db.Exec(ctx, markQACandidatesOfRowStale, arg.FileVersionID, arg.SectionOrdinal, arg.SourceRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reviewCandidate = `-- name: ReviewCandidate :execrows
UPDATE candidates
SET state = $1, question = $2, alternate_questions = $3,
    answer = $4, flags = $5, content_hash = $6,
    review_note = $7, reviewed_at = now()
WHERE id = $8 AND state = 'PENDING_REVIEW'
`

type ReviewCandidateParams struct {
	ToState            string    `json:"toState"`
	Question           string    `json:"question"`
	AlternateQuestions []string  `json:"alternateQuestions"`
	Answer             string    `json:"answer"`
	Flags              []string  `json:"flags"`
	ContentHash        []byte    `json:"contentHash"`
	ReviewNote         *string   `json:"reviewNote"`
	ID                 uuid.UUID `json:"id"`
}

// Applies a decision to a PENDING_REVIEW candidate. The caller has checked the
// edge with domain.CandidateState.Transition.
func (q *Queries) ReviewCandidate(ctx context.Context, arg ReviewCandidateParams) (int64, error) {
	result, err := q.db.Exec(ctx, reviewCandidate,
		arg.ToState,
		arg.Question,
		arg.AlternateQuestions,
		arg.Answer,
		arg.Flags,
		arg.ContentHash,
		arg.ReviewNote,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
