// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalogs.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getLiveCatalog = `-- name: GetLiveCatalog :one
SELECT c.id, c.products
FROM publications p
JOIN product_catalogs c ON c.id = p.catalog_id
WHERE p.language = $1 AND p.state = 'LIVE'
`

type GetLiveCatalogRow struct {
	ID       uuid.UUID `json:"id"`
	Products []byte    `json:"products"`
}

// The catalog the LIVE publication of a language was built with. No row: no
// LIVE publication, or it was built without a catalog.
func (q *Queries) GetLiveCatalog(ctx context.Context, language string) (GetLiveCatalogRow, error) {
	row := q.db.QueryRow(ctx, getLiveCatalog, language)
	var i GetLiveCatalogRow
	err := row.Scan(&i.ID, &i.Products)
	return i, err
}

const getPublicationCatalog = `-- name: GetPublicationCatalog :one
SELECT c.id, c.products
FROM publications p
JOIN product_catalogs c ON c.id = p.catalog_id
WHERE p.id = $1
`

type GetPublicationCatalogRow struct {
	ID       uuid.UUID `json:"id"`
	Products []byte    `json:"products"`
}

func (q *Queries) GetPublicationCatalog(ctx context.Context, id uuid.UUID) (GetPublicationCatalogRow, error) {
	row := q.db.QueryRow(ctx, getPublicationCatalog, id)
	var i GetPublicationCatalogRow
	err := row.Scan(&i.ID, &i.Products)
	return i, err
}

const insertProductCatalog = `-- name: InsertProductCatalog :one

INSERT INTO product_catalogs (file_version_id, products) VALUES ($1, $2)
ON CONFLICT (file_version_id) DO UPDATE SET products = EXCLUDED.products
RETURNING id, file_version_id, products, created_at
`

type InsertProductCatalogParams struct {
	FileVersionID uuid.UUID `json:"fileVersionId"`
	Products      []byte    `json:"products"`
}

// SPDX-License-Identifier: Apache-2.0
// Idempotent per file version: a retried parse job writes the same row.
func (q *Queries) InsertProductCatalog(ctx context.Context, arg InsertProductCatalogParams) (ProductCatalog, error) {
	row := q.db.QueryRow(ctx, insertProductCatalog, arg.FileVersionID, arg.Products)
	var i ProductCatalog
	err := row.Scan(
		&i.ID,
		&i.FileVersionID,
		&i.Products,
		&i.CreatedAt,
	)
	return i, err
}

const listCurrentCatalogSources = `-- name: ListCurrentCatalogSources :many
SELECT sf.object_key, v.id AS file_version_id, v.state, v.parse_error_code, c.id AS catalog_id, c.products
FROM source_files sf
JOIN file_versions v ON v.source_file_id = sf.id AND v.superseded_at IS NULL
LEFT JOIN product_catalogs c ON c.file_version_id = v.id
WHERE lower(sf.object_key) LIKE '%products.yaml'
ORDER BY v.last_modified_at DESC, v.id DESC
`

type ListCurrentCatalogSourcesRow struct {
	ObjectKey      string     `json:"objectKey"`
	FileVersionID  uuid.UUID  `json:"fileVersionId"`
	State          string     `json:"state"`
	ParseErrorCode *string    `json:"parseErrorCode"`
	CatalogID      *uuid.UUID `json:"catalogId"`
	Products       []byte     `json:"products"`
}

// The current version of every object named products.yaml (any case, any
// directory), with its stored catalog when it parsed. The caller picks the one
// at the root of the S3 prefix (scan.IsCatalogRoot).
func (q *Queries) ListCurrentCatalogSources(ctx context.Context) ([]ListCurrentCatalogSourcesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentCatalogSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentCatalogSourcesRow{}
	for rows.Next() {
		var i ListCurrentCatalogSourcesRow
		if err := rows.Scan(
			&i.ObjectKey,
			&i.FileVersionID,
			&i.State,
			&i.ParseErrorCode,
			&i.CatalogID,
			&i.Products,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
