// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package queries

import (
	"context"
)

// iteratorForInsertFactRows implements pgx.CopyFromSource.
type iteratorForInsertFactRows struct {
	rows                 []InsertFactRowsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertFactRows) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertFactRows) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FactTableID,
		r.rows[0].WorkbookVersionID,
		r.rows[0].MappingVersionID,
		r.rows[0].Key,
		r.rows[0].Row,
		r.rows[0].ValidFrom,
		r.rows[0].ValidTo,
		r.rows[0].SourceRef,
	}, nil
}

func (r iteratorForInsertFactRows) Err() error {
	return nil
}

func (q *Queries) InsertFactRows(ctx context.Context, arg []InsertFactRowsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"fact_rows"}, []string{"fact_table_id", "workbook_version_id", "mapping_version_id", "key", "row", "valid_from", "valid_to", "source_ref"}, &iteratorForInsertFactRows{rows: arg})
}

// iteratorForInsertParsedSections implements pgx.CopyFromSource.
type iteratorForInsertParsedSections struct {
	rows                 []InsertParsedSectionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertParsedSections) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertParsedSections) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FileVersionID,
		r.rows[0].Ordinal,
		r.rows[0].Kind,
		r.rows[0].HeadingPath,
		r.rows[0].Level,
		r.rows[0].Body,
		r.rows[0].SourceRef,
	}, nil
}

func (r iteratorForInsertParsedSections) Err() error {
	return nil
}

func (q *Queries) InsertParsedSections(ctx context.Context, arg []InsertParsedSectionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"parsed_sections"}, []string{"file_version_id", "ordinal", "kind", "heading_path", "level", "body", "source_ref"}, &iteratorForInsertParsedSections{rows: arg})
}
