// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facts.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearFactTable = `-- name: ClearFactTable :exec
UPDATE fact_tables
SET workbook_version_id = NULL, mapping_version_id = NULL, status = 'UNAVAILABLE',
    last_error_code = $1::text, updated_at = now()
WHERE id = $2
`

type ClearFactTableParams struct {
	ErrorCode string    `json:"errorCode"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) ClearFactTable(ctx context.Context, arg ClearFactTableParams) error {
	_, err := q.db.Exec(ctx, clearFactTable, arg.ErrorCode, arg.ID)
	return err
}

const clearFactTablesForVersion = `-- name: ClearFactTablesForVersion :execrows
UPDATE fact_tables
SET workbook_version_id = NULL, mapping_version_id = NULL, status = 'UNAVAILABLE',
    last_error_code = $1::text, updated_at = now()
WHERE workbook_version_id = $2 OR mapping_version_id = $2
`

type ClearFactTablesForVersionParams struct {
	ErrorCode string     `json:"errorCode"`
	VersionID *uuid.UUID `json:"versionId"`
}

// A file version stopped being the live source (superseded or removed): every
// table whose pointer names it becomes UNAVAILABLE.
func (q *Queries) ClearFactTablesForVersion(ctx context.Context, arg ClearFactTablesForVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearFactTablesForVersion, arg.ErrorCode, arg.VersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFactRows = `-- name: DeleteFactRows :execrows
DELETE FROM fact_rows WHERE fact_table_id = $1
`

func (q *Queries) DeleteFactRows(ctx context.Context, factTableID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFactRows, factTableID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFactTableByName = `-- name: GetFactTableByName :one

SELECT id, name, workbook_source_file_id, mapping_source_file_id, columns, key_columns, workbook_version_id, mapping_version_id, status, last_error_code, updated_at FROM fact_tables WHERE name = $1
`

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetFactTableByName(ctx context.Context, name string) (FactTable, error) {
	row := q.db.QueryRow(ctx, getFactTableByName, name)
	var i FactTable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkbookSourceFileID,
		&i.MappingSourceFileID,
		&i.Columns,
		&i.KeyColumns,
		&i.WorkbookVersionID,
		&i.MappingVersionID,
		&i.Status,
		&i.LastErrorCode,
		&i.UpdatedAt,
	)
	return i, err
}

const getFactTableByNameForUpdate = `-- name: GetFactTableByNameForUpdate :one
SELECT id, name, workbook_source_file_id, mapping_source_file_id, columns, key_columns, workbook_version_id, mapping_version_id, status, last_error_code, updated_at FROM fact_tables WHERE name = $1 FOR UPDATE
`

func (q *Queries) GetFactTableByNameForUpdate(ctx context.Context, name string) (FactTable, error) {
	row := q.db.QueryRow(ctx, getFactTableByNameForUpdate, name)
	var i FactTable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkbookSourceFileID,
		&i.MappingSourceFileID,
		&i.Columns,
		&i.KeyColumns,
		&i.WorkbookVersionID,
		&i.MappingVersionID,
		&i.Status,
		&i.LastErrorCode,
		&i.UpdatedAt,
	)
	return i, err
}

type InsertFactRowsParams struct {
	FactTableID       uuid.UUID   `json:"factTableId"`
	WorkbookVersionID uuid.UUID   `json:"workbookVersionId"`
	MappingVersionID  uuid.UUID   `json:"mappingVersionId"`
	Key               []byte      `json:"key"`
	Row               []byte      `json:"row"`
	ValidFrom         pgtype.Date `json:"validFrom"`
	ValidTo           pgtype.Date `json:"validTo"`
	SourceRef         string      `json:"sourceRef"`
}

const insertFactTable = `-- name: InsertFactTable :one
INSERT INTO fact_tables (name, workbook_source_file_id, mapping_source_file_id, columns, key_columns, status, last_error_code)
VALUES ($1, $2, $3, $4, $5, 'UNAVAILABLE', $6)
RETURNING id, name, workbook_source_file_id, mapping_source_file_id, columns, key_columns, workbook_version_id, mapping_version_id, status, last_error_code, updated_at
`

type InsertFactTableParams struct {
	Name                 string     `json:"name"`
	WorkbookSourceFileID *uuid.UUID `json:"workbookSourceFileId"`
	MappingSourceFileID  uuid.UUID  `json:"mappingSourceFileId"`
	Columns              []byte     `json:"columns"`
	KeyColumns           []string   `json:"keyColumns"`
	LastErrorCode        *string    `json:"lastErrorCode"`
}

// A new table starts UNAVAILABLE; only a complete import points it at rows.
func (q *Queries) InsertFactTable(ctx context.Context, arg InsertFactTableParams) (FactTable, error) {
	row := q.db.QueryRow(ctx, insertFactTable,
		arg.Name,
		arg.WorkbookSourceFileID,
		arg.MappingSourceFileID,
		arg.Columns,
		arg.KeyColumns,
		arg.LastErrorCode,
	)
	var i FactTable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.WorkbookSourceFileID,
		&i.MappingSourceFileID,
		&i.Columns,
		&i.KeyColumns,
		&i.WorkbookVersionID,
		&i.MappingVersionID,
		&i.Status,
		&i.LastErrorCode,
		&i.UpdatedAt,
	)
	return i, err
}

const listFactTablesByMappingSource = `-- name: ListFactTablesByMappingSource :many
SELECT id, name, workbook_source_file_id, mapping_source_file_id, columns, key_columns, workbook_version_id, mapping_version_id, status, last_error_code, updated_at FROM fact_tables WHERE mapping_source_file_id = $1 ORDER BY name FOR UPDATE
`

func (q *Queries) ListFactTablesByMappingSource(ctx context.Context, mappingSourceFileID uuid.UUID) ([]FactTable, error) {
	rows, err := q.db.Query(ctx, listFactTablesByMappingSource, mappingSourceFileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FactTable{}
	for rows.Next() {
		var i FactTable
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.WorkbookSourceFileID,
			&i.MappingSourceFileID,
			&i.Columns,
			&i.KeyColumns,
			&i.WorkbookVersionID,
			&i.MappingVersionID,
			&i.Status,
			&i.LastErrorCode,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupFactRows = `-- name: LookupFactRows :many
SELECT r.row, r.source_ref, r.valid_from, r.valid_to
FROM fact_tables t
JOIN fact_rows r ON r.fact_table_id = t.id
                AND r.workbook_version_id = t.workbook_version_id
                AND r.mapping_version_id = t.mapping_version_id
WHERE t.id = $1
  AND t.status = 'AVAILABLE'
  AND r.key = $2::jsonb
  AND (r.valid_from IS NULL OR r.valid_from <= $3::date)
  AND (r.valid_to IS NULL OR $3::date < r.valid_to)
LIMIT 2
`

type LookupFactRowsParams struct {
	TableID uuid.UUID   `json:"tableId"`
	Key     []byte      `json:"key"`
	At      pgtype.Date `json:"at"`
}

type LookupFactRowsRow struct {
	Row       []byte      `json:"row"`
	SourceRef string      `json:"sourceRef"`
	ValidFrom pgtype.Date `json:"validFrom"`
	ValidTo   pgtype.Date `json:"validTo"`
}

// Exact match on the canonical key within the table's current import pointer,
// valid at the given date (half-open: valid_from <= at < valid_to). LIMIT 2 so
// the caller can tell "more than one" from "one"; import validation makes more
// than one impossible.
func (q *Queries) LookupFactRows(ctx context.Context, arg LookupFactRowsParams) ([]LookupFactRowsRow, error) {
	rows, err := q.db.Query(ctx, lookupFactRows, arg.TableID, arg.Key, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LookupFactRowsRow{}
	for rows.Next() {
		var i LookupFactRowsRow
		if err := rows.Scan(
			&i.Row,
			&i.SourceRef,
			&i.ValidFrom,
			&i.ValidTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFactTablesUnavailableBySource = `-- name: MarkFactTablesUnavailableBySource :execrows
UPDATE fact_tables
SET workbook_version_id = NULL, mapping_version_id = NULL, status = 'UNAVAILABLE',
    last_error_code = $1::text, updated_at = now()
WHERE workbook_source_file_id = $2 OR mapping_source_file_id = $2
`

type MarkFactTablesUnavailableBySourceParams struct {
	ErrorCode    string     `json:"errorCode"`
	SourceFileID *uuid.UUID `json:"sourceFileId"`
}

// Clears the pointer of every table fed by this source file (as workbook or as
// mapping) and records why.
func (q *Queries) MarkFactTablesUnavailableBySource(ctx context.Context, arg MarkFactTablesUnavailableBySourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, markFactTablesUnavailableBySource, arg.ErrorCode, arg.SourceFileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pointFactTable = `-- name: PointFactTable :exec
UPDATE fact_tables
SET workbook_version_id = $2, mapping_version_id = $3, status = 'AVAILABLE', last_error_code = NULL, updated_at = now()
WHERE id = $1
`

type PointFactTableParams struct {
	ID                uuid.UUID  `json:"id"`
	WorkbookVersionID *uuid.UUID `json:"workbookVersionId"`
	MappingVersionID  *uuid.UUID `json:"mappingVersionId"`
}

func (q *Queries) PointFactTable(ctx context.Context, arg PointFactTableParams) error {
	_, err := q.db.Exec(ctx, pointFactTable, arg.ID, arg.WorkbookVersionID, arg.MappingVersionID)
	return err
}

const updateFactTableDefinition = `-- name: UpdateFactTableDefinition :exec
UPDATE fact_tables
SET workbook_source_file_id = $2, mapping_source_file_id = $3, columns = $4, key_columns = $5,
    workbook_version_id = NULL, mapping_version_id = NULL, status = 'UNAVAILABLE', last_error_code = $6, updated_at = now()
WHERE id = $1
`

type UpdateFactTableDefinitionParams struct {
	ID                   uuid.UUID  `json:"id"`
	WorkbookSourceFileID *uuid.UUID `json:"workbookSourceFileId"`
	MappingSourceFileID  uuid.UUID  `json:"mappingSourceFileId"`
	Columns              []byte     `json:"columns"`
	KeyColumns           []string   `json:"keyColumns"`
	LastErrorCode        *string    `json:"lastErrorCode"`
}

// Redefines the table from a newly parsed mapping and clears the pointer: the
// caller sets it again when it imports rows in the same transaction.
func (q *Queries) UpdateFactTableDefinition(ctx context.Context, arg UpdateFactTableDefinitionParams) error {
	_, err := q.db.Exec(ctx, updateFactTableDefinition,
		arg.ID,
		arg.WorkbookSourceFileID,
		arg.MappingSourceFileID,
		arg.Columns,
		arg.KeyColumns,
		arg.LastErrorCode,
	)
	return err
}
