// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET state = 'RUNNING',
    attempts = attempts + 1,
    locked_by = $1::text,
    locked_until = now() + make_interval(secs => $2::float8)
WHERE id = (
    SELECT j.id FROM jobs j
    WHERE j.state = 'QUEUED' AND j.run_after <= now() AND j.kind = ANY($3::text[])
    ORDER BY j.run_after, j.id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, kind, payload, state, attempts, max_attempts, run_after, locked_until, locked_by, last_error_code, last_error_message, created_at, finished_at, dedupe_key
`

type ClaimJobParams struct {
	Worker       string   `json:"worker"`
	LeaseSeconds float64  `json:"leaseSeconds"`
	Kinds        []string `json:"kinds"`
}

// SKIP LOCKED lets concurrent workers each take a different row.
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.Worker, arg.LeaseSeconds, arg.Kinds)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.LockedUntil,
		&i.LockedBy,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.DedupeKey,
	)
	return i, err
}

const claimJobByDedupeKey = `-- name: ClaimJobByDedupeKey :one
UPDATE jobs
SET state = 'RUNNING',
    attempts = attempts + 1,
    locked_by = $1::text,
    locked_until = now() + make_interval(secs => $2::float8)
WHERE id = (
    SELECT j.id FROM jobs j
    WHERE j.state = 'QUEUED' AND j.run_after <= now() AND j.kind = $3::text AND j.dedupe_key = $4::text
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, kind, payload, state, attempts, max_attempts, run_after, locked_until, locked_by, last_error_code, last_error_message, created_at, finished_at, dedupe_key
`

type ClaimJobByDedupeKeyParams struct {
	Worker       string  `json:"worker"`
	LeaseSeconds float64 `json:"leaseSeconds"`
	Kind         string  `json:"kind"`
	DedupeKey    string  `json:"dedupeKey"`
}

// Claims the one job of (kind, dedupe_key) when it is claimable; the operator's
// `generate --version` uses it to work on a single file version.
func (q *Queries) ClaimJobByDedupeKey(ctx context.Context, arg ClaimJobByDedupeKeyParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimJobByDedupeKey,
		arg.Worker,
		arg.LeaseSeconds,
		arg.Kind,
		arg.DedupeKey,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.LockedUntil,
		&i.LockedBy,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.DedupeKey,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :execrows
UPDATE jobs
SET state = 'SUCCEEDED', finished_at = now(), locked_until = NULL, locked_by = NULL
WHERE id = $1 AND state = 'RUNNING' AND locked_by = $2::text
`

type CompleteJobParams struct {
	ID     uuid.UUID `json:"id"`
	Worker string    `json:"worker"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeJob, arg.ID, arg.Worker)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueJob = `-- name: EnqueueJob :execrows

INSERT INTO jobs (kind, payload, dedupe_key, max_attempts, run_after)
VALUES ($1, $2, $3, $4, COALESCE($5::timestamptz, '-infinity'::timestamptz))
ON CONFLICT (kind, dedupe_key) WHERE dedupe_key IS NOT NULL DO NOTHING
`

type EnqueueJobParams struct {
	Kind        string             `json:"kind"`
	Payload     []byte             `json:"payload"`
	DedupeKey   *string            `json:"dedupeKey"`
	MaxAttempts int32              `json:"maxAttempts"`
	RunAfter    pgtype.Timestamptz `json:"runAfter"`
}

// SPDX-License-Identifier: Apache-2.0
// Idempotent per (kind, dedupe_key): a repeat returns 0 rows affected.
// A job with no run_after is due immediately: it is stored as -infinity, not as
// now(), so that it is claimable whatever clock the claiming backend reads. Two
// backends of one server can disagree by hundreds of milliseconds (virtual
// machines with per-CPU counter offsets), and a now() taken by a backend that
// runs ahead would keep a job just committed invisible to the next claim.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueJob,
		arg.Kind,
		arg.Payload,
		arg.DedupeKey,
		arg.MaxAttempts,
		arg.RunAfter,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendJobLease = `-- name: ExtendJobLease :execrows
UPDATE jobs
SET locked_until = now() + make_interval(secs => $1::float8)
WHERE id = $2 AND state = 'RUNNING' AND locked_by = $3::text
`

type ExtendJobLeaseParams struct {
	LeaseSeconds float64   `json:"leaseSeconds"`
	ID           uuid.UUID `json:"id"`
	Worker       string    `json:"worker"`
}

// A long job (generate calls the LLM once per section) keeps its lease alive.
func (q *Queries) ExtendJobLease(ctx context.Context, arg ExtendJobLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, extendJobLease, arg.LeaseSeconds, arg.ID, arg.Worker)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failJob = `-- name: FailJob :execrows
UPDATE jobs
SET state = CASE WHEN attempts >= max_attempts THEN 'FAILED' ELSE 'QUEUED' END,
    finished_at = CASE WHEN attempts >= max_attempts THEN now() ELSE NULL END,
    run_after = CASE WHEN attempts >= max_attempts THEN run_after
                     ELSE now() + make_interval(secs => LEAST($1::float8, $2::float8 * power(2, attempts - 1))) END,
    last_error_code = $3::text,
    last_error_message = $4::text,
    locked_until = NULL,
    locked_by = NULL
WHERE id = $5 AND state = 'RUNNING' AND locked_by = $6::text
`

type FailJobParams struct {
	CapSeconds   float64   `json:"capSeconds"`
	BaseSeconds  float64   `json:"baseSeconds"`
	ErrorCode    string    `json:"errorCode"`
	ErrorMessage string    `json:"errorMessage"`
	ID           uuid.UUID `json:"id"`
	Worker       string    `json:"worker"`
}

// Retry with exponential backoff (base * 2^(attempts-1), capped), or FAILED
// once attempts reached max_attempts.
func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, failJob,
		arg.CapSeconds,
		arg.BaseSeconds,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.Worker,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJob = `-- name: GetJob :one
SELECT id, kind, payload, state, attempts, max_attempts, run_after, locked_until, locked_by, last_error_code, last_error_message, created_at, finished_at, dedupe_key FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.State,
		&i.Attempts,
		&i.MaxAttempts,
		&i.RunAfter,
		&i.LockedUntil,
		&i.LockedBy,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.DedupeKey,
	)
	return i, err
}

const rearmJob = `-- name: RearmJob :execrows
UPDATE jobs
SET state = 'QUEUED', attempts = 0, run_after = '-infinity'::timestamptz, finished_at = NULL,
    locked_until = NULL, locked_by = NULL, last_error_code = NULL, last_error_message = NULL
WHERE kind = $1 AND dedupe_key = $2::text AND state IN ('SUCCEEDED', 'FAILED')
`

type RearmJobParams struct {
	Kind      string `json:"kind"`
	DedupeKey string `json:"dedupeKey"`
}

// Operator retry: puts a finished job back in the queue with a fresh attempt
// budget. A QUEUED or RUNNING job is left alone.
func (q *Queries) RearmJob(ctx context.Context, arg RearmJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, rearmJob, arg.Kind, arg.DedupeKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reclaimExpiredJobs = `-- name: ReclaimExpiredJobs :execrows
UPDATE jobs
SET state = CASE WHEN attempts >= max_attempts THEN 'FAILED' ELSE 'QUEUED' END,
    finished_at = CASE WHEN attempts >= max_attempts THEN now() ELSE NULL END,
    last_error_code = 'LEASE_EXPIRED',
    last_error_message = 'lease expired before the worker finished',
    locked_until = NULL,
    locked_by = NULL
WHERE state = 'RUNNING' AND locked_until < now()
`

// A RUNNING job whose lease ran out goes back to QUEUED, or to FAILED when it
// has used all its attempts (the claim that expired was its last one).
func (q *Queries) ReclaimExpiredJobs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, reclaimExpiredJobs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
