// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type APIKey struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"keyPrefix"`
	KeyHash    []byte             `json:"keyHash"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	LastUsedAt pgtype.Timestamptz `json:"lastUsedAt"`
	RevokedAt  pgtype.Timestamptz `json:"revokedAt"`
}

type Candidate struct {
	ID                 uuid.UUID          `json:"id"`
	FileVersionID      uuid.UUID          `json:"fileVersionId"`
	Language           string             `json:"language"`
	Question           string             `json:"question"`
	AlternateQuestions []string           `json:"alternateQuestions"`
	Answer             string             `json:"answer"`
	SourceRef          string             `json:"sourceRef"`
	Flags              []string           `json:"flags"`
	State              string             `json:"state"`
	ContentHash        []byte             `json:"contentHash"`
	ReviewNote         *string            `json:"reviewNote"`
	ReviewedAt         pgtype.Timestamptz `json:"reviewedAt"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	SectionOrdinal     *int32             `json:"sectionOrdinal"`
	PromptVersion      string             `json:"promptVersion"`
	Model              string             `json:"model"`
	GeneratedAt        pgtype.Timestamptz `json:"generatedAt"`
}

type CandidateReview struct {
	ID             uuid.UUID          `json:"id"`
	CandidateID    uuid.UUID          `json:"candidateId"`
	Action         string             `json:"action"`
	Reviewer       string             `json:"reviewer"`
	Before         []byte             `json:"before"`
	After          []byte             `json:"after"`
	SourceFileName string             `json:"sourceFileName"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewedAt"`
}

type FactRow struct {
	ID                uuid.UUID   `json:"id"`
	FactTableID       uuid.UUID   `json:"factTableId"`
	WorkbookVersionID uuid.UUID   `json:"workbookVersionId"`
	MappingVersionID  uuid.UUID   `json:"mappingVersionId"`
	Key               []byte      `json:"key"`
	Row               []byte      `json:"row"`
	ValidFrom         pgtype.Date `json:"validFrom"`
	ValidTo           pgtype.Date `json:"validTo"`
	SourceRef         string      `json:"sourceRef"`
}

type FactTable struct {
	ID                   uuid.UUID          `json:"id"`
	Name                 string             `json:"name"`
	WorkbookSourceFileID *uuid.UUID         `json:"workbookSourceFileId"`
	MappingSourceFileID  uuid.UUID          `json:"mappingSourceFileId"`
	Columns              []byte             `json:"columns"`
	KeyColumns           []string           `json:"keyColumns"`
	WorkbookVersionID    *uuid.UUID         `json:"workbookVersionId"`
	MappingVersionID     *uuid.UUID         `json:"mappingVersionId"`
	Status               string             `json:"status"`
	LastErrorCode        *string            `json:"lastErrorCode"`
	UpdatedAt            pgtype.Timestamptz `json:"updatedAt"`
}

type FileVersion struct {
	ID             uuid.UUID          `json:"id"`
	SourceFileID   uuid.UUID          `json:"sourceFileId"`
	VersionNo      int32              `json:"versionNo"`
	SHA256         []byte             `json:"sha256"`
	SizeBytes      int64              `json:"sizeBytes"`
	Etag           string             `json:"etag"`
	LastModifiedAt pgtype.Timestamptz `json:"lastModifiedAt"`
	State          string             `json:"state"`
	ParseErrorCode *string            `json:"parseErrorCode"`
	ParseWarnings  []byte             `json:"parseWarnings"`
	DiscoveredAt   pgtype.Timestamptz `json:"discoveredAt"`
	SupersededAt   pgtype.Timestamptz `json:"supersededAt"`
}

type Job struct {
	ID               uuid.UUID          `json:"id"`
	Kind             string             `json:"kind"`
	Payload          []byte             `json:"payload"`
	State            string             `json:"state"`
	Attempts         int32              `json:"attempts"`
	MaxAttempts      int32              `json:"maxAttempts"`
	RunAfter         pgtype.Timestamptz `json:"runAfter"`
	LockedUntil      pgtype.Timestamptz `json:"lockedUntil"`
	LockedBy         *string            `json:"lockedBy"`
	LastErrorCode    *string            `json:"lastErrorCode"`
	LastErrorMessage *string            `json:"lastErrorMessage"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	FinishedAt       pgtype.Timestamptz `json:"finishedAt"`
	DedupeKey        *string            `json:"dedupeKey"`
}

type ParsedSection struct {
	ID            uuid.UUID `json:"id"`
	FileVersionID uuid.UUID `json:"fileVersionId"`
	Ordinal       int32     `json:"ordinal"`
	Kind          string    `json:"kind"`
	HeadingPath   []string  `json:"headingPath"`
	Level         int32     `json:"level"`
	Body          string    `json:"body"`
	SourceRef     string    `json:"sourceRef"`
	QaQuestion    *string   `json:"qaQuestion"`
	QaAlternates  []string  `json:"qaAlternates"`
	QaLanguage    *string   `json:"qaLanguage"`
}

type ProductCatalog struct {
	ID            uuid.UUID          `json:"id"`
	FileVersionID uuid.UUID          `json:"fileVersionId"`
	Products      []byte             `json:"products"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
}

type Publication struct {
	ID           uuid.UUID          `json:"id"`
	Language     string             `json:"language"`
	IndexUid     string             `json:"indexUid"`
	State        string             `json:"state"`
	ItemCount    int32              `json:"itemCount"`
	ErrorCode    *string            `json:"errorCode"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	LiveAt       pgtype.Timestamptz `json:"liveAt"`
	SupersededAt pgtype.Timestamptz `json:"supersededAt"`
	ContentUid   *string            `json:"contentUid"`
	CatalogID    *uuid.UUID         `json:"catalogId"`
}

type PublicationItem struct {
	PublicationID      uuid.UUID `json:"publicationId"`
	CandidateID        uuid.UUID `json:"candidateId"`
	ContentHash        []byte    `json:"contentHash"`
	Question           string    `json:"question"`
	AlternateQuestions []string  `json:"alternateQuestions"`
	Answer             string    `json:"answer"`
	SourceRef          string    `json:"sourceRef"`
	Scope              []byte    `json:"scope"`
	Products           []string  `json:"products"`
}

type SourceFile struct {
	ID                     uuid.UUID          `json:"id"`
	Bucket                 string             `json:"bucket"`
	ObjectKey              string             `json:"objectKey"`
	FirstSeenAt            pgtype.Timestamptz `json:"firstSeenAt"`
	LastSeenAt             pgtype.Timestamptz `json:"lastSeenAt"`
	ObservedSizeBytes      *int64             `json:"observedSizeBytes"`
	ObservedEtag           *string            `json:"observedEtag"`
	ObservedLastModifiedAt pgtype.Timestamptz `json:"observedLastModifiedAt"`
}
