// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parse.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteParsedSections = `-- name: DeleteParsedSections :execrows
DELETE FROM parsed_sections WHERE file_version_id = $1
`

func (q *Queries) DeleteParsedSections(ctx context.Context, fileVersionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteParsedSections, fileVersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCurrentVersionByObjectKey = `-- name: GetCurrentVersionByObjectKey :one
SELECT v.id, v.source_file_id, v.version_no, v.sha256, v.size_bytes, v.state, v.superseded_at,
       sf.bucket, sf.object_key
FROM source_files sf
JOIN file_versions v ON v.source_file_id = sf.id AND v.superseded_at IS NULL
WHERE sf.bucket = $1 AND sf.object_key = $2
`

type GetCurrentVersionByObjectKeyParams struct {
	Bucket    string `json:"bucket"`
	ObjectKey string `json:"objectKey"`
}

type GetCurrentVersionByObjectKeyRow struct {
	ID           uuid.UUID          `json:"id"`
	SourceFileID uuid.UUID          `json:"sourceFileId"`
	VersionNo    int32              `json:"versionNo"`
	SHA256       []byte             `json:"sha256"`
	SizeBytes    int64              `json:"sizeBytes"`
	State        string             `json:"state"`
	SupersededAt pgtype.Timestamptz `json:"supersededAt"`
	Bucket       string             `json:"bucket"`
	ObjectKey    string             `json:"objectKey"`
}

// The current (not superseded, not removed) version of one object, if any.
func (q *Queries) GetCurrentVersionByObjectKey(ctx context.Context, arg GetCurrentVersionByObjectKeyParams) (GetCurrentVersionByObjectKeyRow, error) {
	row := q.db.QueryRow(ctx, getCurrentVersionByObjectKey, arg.Bucket, arg.ObjectKey)
	var i GetCurrentVersionByObjectKeyRow
	err := row.Scan(
		&i.ID,
		&i.SourceFileID,
		&i.VersionNo,
		&i.SHA256,
		&i.SizeBytes,
		&i.State,
		&i.SupersededAt,
		&i.Bucket,
		&i.ObjectKey,
	)
	return i, err
}

const getCurrentVersionOfSourceFile = `-- name: GetCurrentVersionOfSourceFile :one
SELECT id, state FROM file_versions WHERE source_file_id = $1 AND superseded_at IS NULL
`

type GetCurrentVersionOfSourceFileRow struct {
	ID    uuid.UUID `json:"id"`
	State string    `json:"state"`
}

// Not locking: used to check whether another source file still has a live
// version.
func (q *Queries) GetCurrentVersionOfSourceFile(ctx context.Context, sourceFileID uuid.UUID) (GetCurrentVersionOfSourceFileRow, error) {
	row := q.db.QueryRow(ctx, getCurrentVersionOfSourceFile, sourceFileID)
	var i GetCurrentVersionOfSourceFileRow
	err := row.Scan(&i.ID, &i.State)
	return i, err
}

const getFileVersionWithSource = `-- name: GetFileVersionWithSource :one

SELECT v.id, v.source_file_id, v.version_no, v.sha256, v.size_bytes, v.state, v.superseded_at,
       sf.bucket, sf.object_key
FROM file_versions v
JOIN source_files sf ON sf.id = v.source_file_id
WHERE v.id = $1
`

type GetFileVersionWithSourceRow struct {
	ID           uuid.UUID          `json:"id"`
	SourceFileID uuid.UUID          `json:"sourceFileId"`
	VersionNo    int32              `json:"versionNo"`
	SHA256       []byte             `json:"sha256"`
	SizeBytes    int64              `json:"sizeBytes"`
	State        string             `json:"state"`
	SupersededAt pgtype.Timestamptz `json:"supersededAt"`
	Bucket       string             `json:"bucket"`
	ObjectKey    string             `json:"objectKey"`
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetFileVersionWithSource(ctx context.Context, id uuid.UUID) (GetFileVersionWithSourceRow, error) {
	row := q.db.QueryRow(ctx, getFileVersionWithSource, id)
	var i GetFileVersionWithSourceRow
	err := row.Scan(
		&i.ID,
		&i.SourceFileID,
		&i.VersionNo,
		&i.SHA256,
		&i.SizeBytes,
		&i.State,
		&i.SupersededAt,
		&i.Bucket,
		&i.ObjectKey,
	)
	return i, err
}

const getSourceFileByObjectKey = `-- name: GetSourceFileByObjectKey :one
SELECT id, bucket, object_key, first_seen_at, last_seen_at, observed_size_bytes, observed_etag, observed_last_modified_at FROM source_files WHERE bucket = $1 AND object_key = $2
`

type GetSourceFileByObjectKeyParams struct {
	Bucket    string `json:"bucket"`
	ObjectKey string `json:"objectKey"`
}

func (q *Queries) GetSourceFileByObjectKey(ctx context.Context, arg GetSourceFileByObjectKeyParams) (SourceFile, error) {
	row := q.db.QueryRow(ctx, getSourceFileByObjectKey, arg.Bucket, arg.ObjectKey)
	var i SourceFile
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.ObjectKey,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ObservedSizeBytes,
		&i.ObservedEtag,
		&i.ObservedLastModifiedAt,
	)
	return i, err
}

type InsertParsedSectionsParams struct {
	FileVersionID uuid.UUID `json:"fileVersionId"`
	Ordinal       int32     `json:"ordinal"`
	Kind          string    `json:"kind"`
	HeadingPath   []string  `json:"headingPath"`
	Level         int32     `json:"level"`
	Body          string    `json:"body"`
	SourceRef     string    `json:"sourceRef"`
}

const listCurrentFailedFileVersions = `-- name: ListCurrentFailedFileVersions :many
SELECT id, source_file_id, version_no, sha256, size_bytes, etag, last_modified_at, state, parse_error_code, parse_warnings, discovered_at, superseded_at FROM file_versions
WHERE state = 'PARSE_FAILED' AND superseded_at IS NULL
ORDER BY discovered_at, id
FOR UPDATE
`

func (q *Queries) ListCurrentFailedFileVersions(ctx context.Context) ([]FileVersion, error) {
	rows, err := q.db.Query(ctx, listCurrentFailedFileVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileVersion{}
	for rows.Next() {
		var i FileVersion
		if err := rows.Scan(
			&i.ID,
			&i.SourceFileID,
			&i.VersionNo,
			&i.SHA256,
			&i.SizeBytes,
			&i.Etag,
			&i.LastModifiedAt,
			&i.State,
			&i.ParseErrorCode,
			&i.ParseWarnings,
			&i.DiscoveredAt,
			&i.SupersededAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParsedSections = `-- name: ListParsedSections :many
SELECT id, file_version_id, ordinal, kind, heading_path, level, body, source_ref FROM parsed_sections WHERE file_version_id = $1 ORDER BY ordinal
`

func (q *Queries) ListParsedSections(ctx context.Context, fileVersionID uuid.UUID) ([]ParsedSection, error) {
	rows, err := q.db.Query(ctx, listParsedSections, fileVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParsedSection{}
	for rows.Next() {
		var i ParsedSection
		if err := rows.Scan(
			&i.ID,
			&i.FileVersionID,
			&i.Ordinal,
			&i.Kind,
			&i.HeadingPath,
			&i.Level,
			&i.Body,
			&i.SourceRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFileVersion = `-- name: LockFileVersion :one
SELECT id, source_file_id, version_no, sha256, size_bytes, etag, last_modified_at, state, parse_error_code, parse_warnings, discovered_at, superseded_at FROM file_versions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockFileVersion(ctx context.Context, id uuid.UUID) (FileVersion, error) {
	row := q.db.QueryRow(ctx, lockFileVersion, id)
	var i FileVersion
	err := row.Scan(
		&i.ID,
		&i.SourceFileID,
		&i.VersionNo,
		&i.SHA256,
		&i.SizeBytes,
		&i.Etag,
		&i.LastModifiedAt,
		&i.State,
		&i.ParseErrorCode,
		&i.ParseWarnings,
		&i.DiscoveredAt,
		&i.SupersededAt,
	)
	return i, err
}

const setParseWarnings = `-- name: SetParseWarnings :exec
UPDATE file_versions SET parse_warnings = $2 WHERE id = $1 AND state = 'PARSED'
`

type SetParseWarningsParams struct {
	ID            uuid.UUID `json:"id"`
	ParseWarnings []byte    `json:"parseWarnings"`
}

// Re-derived warnings of a PARSED version whose sections were re-derived.
func (q *Queries) SetParseWarnings(ctx context.Context, arg SetParseWarningsParams) error {
	_, err := q.db.Exec(ctx, setParseWarnings, arg.ID, arg.ParseWarnings)
	return err
}

const transitionFileVersion = `-- name: TransitionFileVersion :execrows
UPDATE file_versions
SET state = $1, parse_error_code = $2, parse_warnings = $3
WHERE id = $4 AND state = $5 AND superseded_at IS NULL
`

type TransitionFileVersionParams struct {
	ToState        string    `json:"toState"`
	ParseErrorCode *string   `json:"parseErrorCode"`
	ParseWarnings  []byte    `json:"parseWarnings"`
	ID             uuid.UUID `json:"id"`
	FromState      string    `json:"fromState"`
}

// The caller has checked the edge with domain.FileVersionState.Transition. The
// guard on the old state and on superseded_at makes a lost race affect 0 rows.
func (q *Queries) TransitionFileVersion(ctx context.Context, arg TransitionFileVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionFileVersion,
		arg.ToState,
		arg.ParseErrorCode,
		arg.ParseWarnings,
		arg.ID,
		arg.FromState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
