// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: publications.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const failPublication = `-- name: FailPublication :execrows
UPDATE publications SET state = 'FAILED', error_code = $2, content_uid = NULL
WHERE id = $1 AND state = 'BUILDING'
`

type FailPublicationParams struct {
	ID        uuid.UUID `json:"id"`
	ErrorCode *string   `json:"errorCode"`
}

// BUILDING -> FAILED. The caller has checked the edge with domain.
func (q *Queries) FailPublication(ctx context.Context, arg FailPublicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, failPublication, arg.ID, arg.ErrorCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLivePublication = `-- name: GetLivePublication :one

SELECT id, language, index_uid, state, item_count, error_code, created_at, live_at, superseded_at, content_uid, catalog_id, seq, superseded_seq FROM publications
WHERE language = $1 AND state = 'LIVE'
`

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetLivePublication(ctx context.Context, language string) (Publication, error) {
	row := q.db.QueryRow(ctx, getLivePublication, language)
	var i Publication
	err := row.Scan(
		&i.ID,
		&i.Language,
		&i.IndexUid,
		&i.State,
		&i.ItemCount,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.LiveAt,
		&i.SupersededAt,
		&i.ContentUid,
		&i.CatalogID,
		&i.Seq,
		&i.SupersededSeq,
	)
	return i, err
}

const getPublication = `-- name: GetPublication :one
SELECT id, language, index_uid, state, item_count, error_code, created_at, live_at, superseded_at, content_uid, catalog_id, seq, superseded_seq FROM publications WHERE id = $1
`

func (q *Queries) GetPublication(ctx context.Context, id uuid.UUID) (Publication, error) {
	row := q.db.QueryRow(ctx, getPublication, id)
	var i Publication
	err := row.Scan(
		&i.ID,
		&i.Language,
		&i.IndexUid,
		&i.State,
		&i.ItemCount,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.LiveAt,
		&i.SupersededAt,
		&i.ContentUid,
		&i.CatalogID,
		&i.Seq,
		&i.SupersededSeq,
	)
	return i, err
}

const insertPublication = `-- name: InsertPublication :exec
INSERT INTO publications (id, language, index_uid, catalog_id) VALUES ($1, $2, $3, $4)
`

type InsertPublicationParams struct {
	ID        uuid.UUID  `json:"id"`
	Language  string     `json:"language"`
	IndexUid  string     `json:"indexUid"`
	CatalogID *uuid.UUID `json:"catalogId"`
}

func (q *Queries) InsertPublication(ctx context.Context, arg InsertPublicationParams) error {
	_, err := q.db.Exec(ctx, insertPublication,
		arg.ID,
		arg.Language,
		arg.IndexUid,
		arg.CatalogID,
	)
	return err
}

const insertPublicationItem = `-- name: InsertPublicationItem :exec
INSERT INTO publication_items (publication_id, candidate_id, content_hash, question, alternate_questions, answer, source_ref, scope, products)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertPublicationItemParams struct {
	PublicationID      uuid.UUID `json:"publicationId"`
	CandidateID        uuid.UUID `json:"candidateId"`
	ContentHash        []byte    `json:"contentHash"`
	Question           string    `json:"question"`
	AlternateQuestions []string  `json:"alternateQuestions"`
	Answer             string    `json:"answer"`
	SourceRef          string    `json:"sourceRef"`
	Scope              []byte    `json:"scope"`
	Products           []string  `json:"products"`
}

func (q *Queries) InsertPublicationItem(ctx context.Context, arg InsertPublicationItemParams) error {
	_, err := q.db.Exec(ctx, insertPublicationItem,
		arg.PublicationID,
		arg.CandidateID,
		arg.ContentHash,
		arg.Question,
		arg.AlternateQuestions,
		arg.Answer,
		arg.SourceRef,
		arg.Scope,
		arg.Products,
	)
	return err
}

const listBuildingPublications = `-- name: ListBuildingPublications :many
SELECT id, language, index_uid, state, item_count, error_code, created_at, live_at, superseded_at, content_uid, catalog_id, seq, superseded_seq FROM publications WHERE language = $1 AND state = 'BUILDING' ORDER BY seq
`

func (q *Queries) ListBuildingPublications(ctx context.Context, language string) ([]Publication, error) {
	rows, err := q.db.Query(ctx, listBuildingPublications, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Publication{}
	for rows.Next() {
		var i Publication
		if err := rows.Scan(
			&i.ID,
			&i.Language,
			&i.IndexUid,
			&i.State,
			&i.ItemCount,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.LiveAt,
			&i.SupersededAt,
			&i.ContentUid,
			&i.CatalogID,
			&i.Seq,
			&i.SupersededSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicationItems = `-- name: ListPublicationItems :many
SELECT publication_id, candidate_id, content_hash, question, alternate_questions, answer, source_ref, scope, products FROM publication_items WHERE publication_id = $1 ORDER BY candidate_id
`

func (q *Queries) ListPublicationItems(ctx context.Context, publicationID uuid.UUID) ([]PublicationItem, error) {
	rows, err := q.db.Query(ctx, listPublicationItems, publicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublicationItem{}
	for rows.Next() {
		var i PublicationItem
		if err := rows.Scan(
			&i.PublicationID,
			&i.CandidateID,
			&i.ContentHash,
			&i.Question,
			&i.AlternateQuestions,
			&i.Answer,
			&i.SourceRef,
			&i.Scope,
			&i.Products,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicationsOfLanguage = `-- name: ListPublicationsOfLanguage :many
SELECT id, language, index_uid, state, item_count, error_code, created_at, live_at, superseded_at, content_uid, catalog_id, seq, superseded_seq FROM publications WHERE language = $1 ORDER BY seq
`

func (q *Queries) ListPublicationsOfLanguage(ctx context.Context, language string) ([]Publication, error) {
	rows, err := q.db.Query(ctx, listPublicationsOfLanguage, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Publication{}
	for rows.Next() {
		var i Publication
		if err := rows.Scan(
			&i.ID,
			&i.Language,
			&i.IndexUid,
			&i.State,
			&i.ItemCount,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.LiveAt,
			&i.SupersededAt,
			&i.ContentUid,
			&i.CatalogID,
			&i.Seq,
			&i.SupersededSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupersededPublications = `-- name: ListSupersededPublications :many
SELECT id, language, index_uid, state, item_count, error_code, created_at, live_at, superseded_at, content_uid, catalog_id, seq, superseded_seq FROM publications WHERE language = $1 AND state = 'SUPERSEDED'
ORDER BY superseded_seq DESC
`

// Most recently superseded first (superseded_seq, never a timestamp): the
// default rollback target is the first row, and retention keeps the first N.
func (q *Queries) ListSupersededPublications(ctx context.Context, language string) ([]Publication, error) {
	rows, err := q.db.Query(ctx, listSupersededPublications, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Publication{}
	for rows.Next() {
		var i Publication
		if err := rows.Scan(
			&i.ID,
			&i.Language,
			&i.IndexUid,
			&i.State,
			&i.ItemCount,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.LiveAt,
			&i.SupersededAt,
			&i.ContentUid,
			&i.CatalogID,
			&i.Seq,
			&i.SupersededSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLivePublication = `-- name: LockLivePublication :one
SELECT id, language, index_uid, state, item_count, error_code, created_at, live_at, superseded_at, content_uid, catalog_id, seq, superseded_seq FROM publications WHERE language = $1 AND state = 'LIVE' FOR UPDATE
`

func (q *Queries) LockLivePublication(ctx context.Context, language string) (Publication, error) {
	row := q.db.QueryRow(ctx, lockLivePublication, language)
	var i Publication
	err := row.Scan(
		&i.ID,
		&i.Language,
		&i.IndexUid,
		&i.State,
		&i.ItemCount,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.LiveAt,
		&i.SupersededAt,
		&i.ContentUid,
		&i.CatalogID,
		&i.Seq,
		&i.SupersededSeq,
	)
	return i, err
}

const lockPublication = `-- name: LockPublication :one
SELECT id, language, index_uid, state, item_count, error_code, created_at, live_at, superseded_at, content_uid, catalog_id, seq, superseded_seq FROM publications WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPublication(ctx context.Context, id uuid.UUID) (Publication, error) {
	row := q.db.QueryRow(ctx, lockPublication, id)
	var i Publication
	err := row.Scan(
		&i.ID,
		&i.Language,
		&i.IndexUid,
		&i.State,
		&i.ItemCount,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.LiveAt,
		&i.SupersededAt,
		&i.ContentUid,
		&i.CatalogID,
		&i.Seq,
		&i.SupersededSeq,
	)
	return i, err
}

const promotePublication = `-- name: PromotePublication :execrows
UPDATE publications SET state = 'LIVE', live_at = now(), superseded_at = NULL, superseded_seq = NULL, content_uid = $1, error_code = NULL
WHERE id = $2 AND state = $3
`

type PromotePublicationParams struct {
	ContentUid *string   `json:"contentUid"`
	ID         uuid.UUID `json:"id"`
	FromState  string    `json:"fromState"`
}

// BUILDING -> LIVE (publish) or SUPERSEDED -> LIVE (rollback). The caller has
// checked the edge, and demoted the current LIVE row first.
func (q *Queries) PromotePublication(ctx context.Context, arg PromotePublicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, promotePublication, arg.ContentUid, arg.ID, arg.FromState)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPublicationContentUID = `-- name: SetPublicationContentUID :exec
UPDATE publications SET content_uid = $1 WHERE id = $2
`

type SetPublicationContentUIDParams struct {
	ContentUid *string   `json:"contentUid"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) SetPublicationContentUID(ctx context.Context, arg SetPublicationContentUIDParams) error {
	_, err := q.db.Exec(ctx, setPublicationContentUID, arg.ContentUid, arg.ID)
	return err
}

const setPublicationItemCount = `-- name: SetPublicationItemCount :exec
UPDATE publications SET item_count = $2 WHERE id = $1
`

type SetPublicationItemCountParams struct {
	ID        uuid.UUID `json:"id"`
	ItemCount int32     `json:"itemCount"`
}

func (q *Queries) SetPublicationItemCount(ctx context.Context, arg SetPublicationItemCountParams) error {
	_, err := q.db.Exec(ctx, setPublicationItemCount, arg.ID, arg.ItemCount)
	return err
}

const supersedePublication = `-- name: SupersedePublication :execrows
UPDATE publications SET state = 'SUPERSEDED', superseded_at = now(), superseded_seq = nextval('publication_superseded_seq'), content_uid = $1
WHERE id = $2 AND state = 'LIVE'
`

type SupersedePublicationParams struct {
	ContentUid *string   `json:"contentUid"`
	ID         uuid.UUID `json:"id"`
}

// LIVE -> SUPERSEDED. content_uid is where the content lives now (NULL when no
// index holds it).
func (q *Queries) SupersedePublication(ctx context.Context, arg SupersedePublicationParams) (int64, error) {
	result, err := q.db.Exec(ctx, supersedePublication, arg.ContentUid, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
