// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scan.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentFileVersion = `-- name: GetCurrentFileVersion :one
SELECT id, source_file_id, version_no, sha256, size_bytes, etag, last_modified_at, state, parse_error_code, parse_warnings, discovered_at, superseded_at FROM file_versions
WHERE source_file_id = $1 AND superseded_at IS NULL
FOR UPDATE
`

func (q *Queries) GetCurrentFileVersion(ctx context.Context, sourceFileID uuid.UUID) (FileVersion, error) {
	row := q.db.QueryRow(ctx, getCurrentFileVersion, sourceFileID)
	var i FileVersion
	err := row.Scan(
		&i.ID,
		&i.SourceFileID,
		&i.VersionNo,
		&i.SHA256,
		&i.SizeBytes,
		&i.Etag,
		&i.LastModifiedAt,
		&i.State,
		&i.ParseErrorCode,
		&i.ParseWarnings,
		&i.DiscoveredAt,
		&i.SupersededAt,
	)
	return i, err
}

const insertFileVersion = `-- name: InsertFileVersion :one
INSERT INTO file_versions (source_file_id, version_no, sha256, size_bytes, etag, last_modified_at, state, parse_error_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, source_file_id, version_no, sha256, size_bytes, etag, last_modified_at, state, parse_error_code, parse_warnings, discovered_at, superseded_at
`

type InsertFileVersionParams struct {
	SourceFileID   uuid.UUID          `json:"sourceFileId"`
	VersionNo      int32              `json:"versionNo"`
	SHA256         []byte             `json:"sha256"`
	SizeBytes      int64              `json:"sizeBytes"`
	Etag           string             `json:"etag"`
	LastModifiedAt pgtype.Timestamptz `json:"lastModifiedAt"`
	State          string             `json:"state"`
	ParseErrorCode *string            `json:"parseErrorCode"`
}

func (q *Queries) InsertFileVersion(ctx context.Context, arg InsertFileVersionParams) (FileVersion, error) {
	row := q.db.QueryRow(ctx, insertFileVersion,
		arg.SourceFileID,
		arg.VersionNo,
		arg.SHA256,
		arg.SizeBytes,
		arg.Etag,
		arg.LastModifiedAt,
		arg.State,
		arg.ParseErrorCode,
	)
	var i FileVersion
	err := row.Scan(
		&i.ID,
		&i.SourceFileID,
		&i.VersionNo,
		&i.SHA256,
		&i.SizeBytes,
		&i.Etag,
		&i.LastModifiedAt,
		&i.State,
		&i.ParseErrorCode,
		&i.ParseWarnings,
		&i.DiscoveredAt,
		&i.SupersededAt,
	)
	return i, err
}

const listPublishableCandidates = `-- name: ListPublishableCandidates :many
SELECT c.id, c.file_version_id, c.language, c.question, c.alternate_questions, c.answer, c.source_ref, c.flags, c.state, c.content_hash, c.review_note, c.reviewed_at, c.created_at, c.section_ordinal, c.prompt_version, c.model, c.generated_at, sf.object_key
FROM candidates c
JOIN file_versions v ON v.id = c.file_version_id
JOIN source_files sf ON sf.id = v.source_file_id
WHERE c.language = $1
  AND c.state = 'APPROVED'
  AND v.superseded_at IS NULL
  AND v.state <> 'REMOVED'
ORDER BY c.created_at, c.id
`

type ListPublishableCandidatesRow struct {
	ID                 uuid.UUID          `json:"id"`
	FileVersionID      uuid.UUID          `json:"fileVersionId"`
	Language           string             `json:"language"`
	Question           string             `json:"question"`
	AlternateQuestions []string           `json:"alternateQuestions"`
	Answer             string             `json:"answer"`
	SourceRef          string             `json:"sourceRef"`
	Flags              []string           `json:"flags"`
	State              string             `json:"state"`
	ContentHash        []byte             `json:"contentHash"`
	ReviewNote         *string            `json:"reviewNote"`
	ReviewedAt         pgtype.Timestamptz `json:"reviewedAt"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	SectionOrdinal     *int32             `json:"sectionOrdinal"`
	PromptVersion      string             `json:"promptVersion"`
	Model              string             `json:"model"`
	GeneratedAt        pgtype.Timestamptz `json:"generatedAt"`
	ObjectKey          string             `json:"objectKey"`
}

// The only candidates a publish may read: APPROVED, of a version that is still
// current and not removed. A candidate whose version was superseded or removed
// is STALE already; the join is a second guard so a missed transition can
// never publish old content.
// object_key is the source file's S3 key, from which publish derives the scope.
func (q *Queries) ListPublishableCandidates(ctx context.Context, language string) ([]ListPublishableCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listPublishableCandidates, language)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishableCandidatesRow{}
	for rows.Next() {
		var i ListPublishableCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.FileVersionID,
			&i.Language,
			&i.Question,
			&i.AlternateQuestions,
			&i.Answer,
			&i.SourceRef,
			&i.Flags,
			&i.State,
			&i.ContentHash,
			&i.ReviewNote,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.SectionOrdinal,
			&i.PromptVersion,
			&i.Model,
			&i.GeneratedAt,
			&i.ObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanState = `-- name: ListScanState :many

SELECT sf.id AS source_file_id,
       sf.object_key,
       sf.observed_size_bytes,
       sf.observed_etag,
       sf.observed_last_modified_at,
       v.id        AS version_id,
       v.version_no,
       v.sha256,
       v.state     AS version_state
FROM source_files sf
LEFT JOIN file_versions v ON v.source_file_id = sf.id AND v.superseded_at IS NULL
WHERE sf.bucket = $1
ORDER BY sf.object_key
`

type ListScanStateRow struct {
	SourceFileID           uuid.UUID          `json:"sourceFileId"`
	ObjectKey              string             `json:"objectKey"`
	ObservedSizeBytes      *int64             `json:"observedSizeBytes"`
	ObservedEtag           *string            `json:"observedEtag"`
	ObservedLastModifiedAt pgtype.Timestamptz `json:"observedLastModifiedAt"`
	VersionID              *uuid.UUID         `json:"versionId"`
	VersionNo              *int32             `json:"versionNo"`
	SHA256                 []byte             `json:"sha256"`
	VersionState           *string            `json:"versionState"`
}

// SPDX-License-Identifier: Apache-2.0
// Every source file of a bucket with its current version, if any. A removed
// version is no longer current (superseded_at is set), so a removed file shows
// up here with a NULL version_id.
func (q *Queries) ListScanState(ctx context.Context, bucket string) ([]ListScanStateRow, error) {
	rows, err := q.db.Query(ctx, listScanState, bucket)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScanStateRow{}
	for rows.Next() {
		var i ListScanStateRow
		if err := rows.Scan(
			&i.SourceFileID,
			&i.ObjectKey,
			&i.ObservedSizeBytes,
			&i.ObservedEtag,
			&i.ObservedLastModifiedAt,
			&i.VersionID,
			&i.VersionNo,
			&i.SHA256,
			&i.VersionState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCandidatesStale = `-- name: MarkCandidatesStale :execrows
UPDATE candidates SET state = 'STALE'
WHERE file_version_id = $1 AND state <> 'STALE'
`

// Every candidate state has an edge to STALE (domain.CandidateStates; checked
// by a test), so this is one statement for the whole version.
func (q *Queries) MarkCandidatesStale(ctx context.Context, fileVersionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markCandidatesStale, fileVersionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nextVersionNo = `-- name: NextVersionNo :one
SELECT (COALESCE(MAX(version_no), 0) + 1)::int AS version_no
FROM file_versions
WHERE source_file_id = $1
`

func (q *Queries) NextVersionNo(ctx context.Context, sourceFileID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextVersionNo, sourceFileID)
	var version_no int32
	err := row.Scan(&version_no)
	return version_no, err
}

const removeFileVersion = `-- name: RemoveFileVersion :execrows
UPDATE file_versions SET state = 'REMOVED', superseded_at = now()
WHERE id = $1 AND superseded_at IS NULL
`

// The caller has checked the edge with domain.FileVersionState.Transition.
func (q *Queries) RemoveFileVersion(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, removeFileVersion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeFileVersion = `-- name: SupersedeFileVersion :execrows
UPDATE file_versions SET superseded_at = now()
WHERE id = $1 AND superseded_at IS NULL
`

func (q *Queries) SupersedeFileVersion(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeFileVersion, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateObservedMetadata = `-- name: UpdateObservedMetadata :exec
UPDATE source_files
SET observed_size_bytes = $2, observed_etag = $3, observed_last_modified_at = $4, last_seen_at = now()
WHERE id = $1
`

type UpdateObservedMetadataParams struct {
	ID                     uuid.UUID          `json:"id"`
	ObservedSizeBytes      *int64             `json:"observedSizeBytes"`
	ObservedEtag           *string            `json:"observedEtag"`
	ObservedLastModifiedAt pgtype.Timestamptz `json:"observedLastModifiedAt"`
}

func (q *Queries) UpdateObservedMetadata(ctx context.Context, arg UpdateObservedMetadataParams) error {
	_, err := q.db.Exec(ctx, updateObservedMetadata,
		arg.ID,
		arg.ObservedSizeBytes,
		arg.ObservedEtag,
		arg.ObservedLastModifiedAt,
	)
	return err
}

const upsertSourceFile = `-- name: UpsertSourceFile :one
INSERT INTO source_files (bucket, object_key)
VALUES ($1, $2)
ON CONFLICT (bucket, object_key) DO UPDATE SET last_seen_at = now()
RETURNING id, bucket, object_key, first_seen_at, last_seen_at, observed_size_bytes, observed_etag, observed_last_modified_at
`

type UpsertSourceFileParams struct {
	Bucket    string `json:"bucket"`
	ObjectKey string `json:"objectKey"`
}

// Creates the row or locks the existing one for the rest of the transaction.
func (q *Queries) UpsertSourceFile(ctx context.Context, arg UpsertSourceFileParams) (SourceFile, error) {
	row := q.db.QueryRow(ctx, upsertSourceFile, arg.Bucket, arg.ObjectKey)
	var i SourceFile
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.ObjectKey,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ObservedSizeBytes,
		&i.ObservedEtag,
		&i.ObservedLastModifiedAt,
	)
	return i, err
}
